version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: genadislawa/pethouse:latest
    container_name: pethouse-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pethouse

  db:
    image: mysql:5.7
    container_name: pethouse-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - pethouse

  nginx:
    image: nginx:alpine
    container_name: pethouse-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pethouse

networks:
  pethouse:
    driver: bridge
